language: node_js
notifications:
  email: false
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm i
if: type = pull_request
script:
  - npm t
  - npm run coverage
