version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_labels:
      - 'internal'
    allowed_updates:
      - match:
          update_type: 'security'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
